version: "3.9"

services:
  postgresdb:
    image: postgres:14.3
    environment:
      - POSTGRES_USER=postgres_test
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=postgres
    ports:
      - 54325:5432
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 30s
      retries: 30
  
  redis:
    image: redis:6-bullseye
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
