name: Bumpversion

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: "Version to bump?"
        required: true
        default: patch
        options:
          - patch
          - minor
          - major

concurrency:
  group: bumpversion-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false

jobs:
  bump_the_version:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: "Checkout repository"
        uses: 'actions/checkout@v3'
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
          token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: "Install bump2version"
        run: pip install --upgrade bump2version

      - name: "Bump the version"
        run: |
          bump2version ${{ github.event.inputs.version }}
      
      - name: "Push Tag"
        uses: actions-ecosystem/action-push-tag@v1
        with:
          tag: ${{ github.event.inputs.version }}
