name: Run coverage
on:
  pull_request:

concurrency:
  group: coverage-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run coverage
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go 1.19
        uses: actions/setup-go@v1
        with:
          go-version: 1.19
        id: go
     
      - name: Checkout repository
        uses: actions/checkout@v3
     
      - name: Get dependencies
        run: go mod download
     
      - name: Run coverage
        run: make test-coverage
