name: Release new version
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Define a tag"
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tag
        uses: actions/checkout@v3
        with:
          ref: "refs/tags/${{ github.event.inputs.tag }}"
      - name: Publish to pkg.go
        env:
          GOPROXY: proxy.golang.org 
          RELEASE_VERSION: ${{ github.event.inputs.tag }}
        run: |
          git config --global user.name "keremdokumaci"
          git config --global user.email "dokumaci.kerem@gmail.com"
          GOPROXY=${{ env.GOPROXY }} go list -m github.com/keremdokumaci/goql@${{ env.RELEASE_VERSION }}